version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: build
      include: scope

  - package-ecosystem: nix
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: nixpkgs
    commit-message:
      prefix: build
      include: scope
